format = """
[░▒▓](#becec8)\
[ 󰣇 ](bg:#becec8 fg:#43544e)\
[](bg:#98a9a3 fg:#becec8)\
$directory\
[](fg:#98a9a3 bg:#698077)\
$git_branch\
$git_status\
[](fg:#698077 bg:#556962)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#556962 bg:#43544e)\
$time\
[ ](fg:#43544e)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#98a9a3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#698077"
format = '[[ $symbol $branch ](fg:#e3e5e5 bg:#698077)]($style)'

[git_status]
style = "bg:#698077"
format = '[[($all_status$ahead_behind )](fg:#e3e5e5 bg:#698077)]($style)'

[nodejs]
symbol = ""
style = "bg:#556962"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#556962"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#556962"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#556962"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#43544e"
format = '[[  $time ](fg:#becec8 bg:#43544e)]($style)'
